---
- include_tasks: variables.yml
- include_tasks: asserts.yml
- name: assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: yes
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

    #- name: install bridge netdev
    #  template:
    #    src: br0.netdev.j2
    #    dest: /etc/systemd/network/br0.netdev
    #    owner: root
    #    group: root
    #    mode: 0644
    #
    #- name: bind interface to bridge
    #  template:
    #    src: 1-br0-bind.network.j2
    #    dest: /etc/systemd/network/1-br0-bind.network
    #    owner: root
    #    group: root
    #    mode: 0644
    #
    #- name: define bridge network
    #  template:
    #    src: 2-br0.network.j2
    #    dest: /etc/systemd/network/2-br0.network
    #    owner: root
    #    group: root
    #    mode: 0644

    #- name: Create dist config dir
    #  file:
    #    path: /etc/libvirt/conf.dist
    #    state: directory
    #    owner: root
    #    group: root
    #    mode: 0755
    #
    #- name: List all config files
    #  find:
    #    path: /etc/libvirt
    #    pattern: "*.conf"
    #  register: __dist_conf_list
    #
    #- name: Compute config file basename 
    #  set_fact:
    #    _conf_list: "{{ _conf_list }} + ['{{ item.path | basename }}']"
    #  loop: "{{ __dist_conf_list.files }}"
    #
    #- name: Copy config file to conf.dist
    #  copy:
    #    remote_src: true
    #    src: "/etc/libvirt/{{ item }}"
    #    dest: "/etc/libvirt/conf.dist/{{ item }}.dist"
    #  loop: "{{ _conf_list }}"
    #
    #- name: Remove config file
    #  file:
    #    path: "/etc/libvirt/{{ item }}"
    #    state: absent
    #  loop: "{{ _conf_list }}"



- name: Include tls
  include_tasks: tls.yml
  when: virtproxyd_cfg.x509 is defined

- name: Include config
  include_tasks: config.yml

- name: add users to group
  user:
    name: "{{ item }}"
    state: present
    groups: "{{ _libvirt_group }}"
    append: yes
  loop: "{{ libvirt_group_members }}" 

